/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32f103x6.h"
#include "Stm32_F103C6_GPIO_Driver.h"
#include "Keypad.h"
#include "lcd.h"

//7 Segments Hex code
#define ZERO 0xC0
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x99
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0xF8
#define EIGHT 0x00
#define NINE 0x10





void clock_init()
{
	//Init clock for GPIOA
	RCC_GPIOA_CLK_EN();

	//Init clock for GPIOB
	RCC_GPIOB_CLK_EN() ;
}

void GPIO_init()
{
	GPIO_PinConfig_t PinCfg ;

	//PORTA.1  input floating mode
	PinCfg.GPIO_PinNumber = GPIO_Pin_9 ;
	PinCfg.GPIO_Mode = GPIO_Mode_Output_PP;
	PinCfg.GPIO_Output_Speed = GPIO_Speed_10M ;
	MCAL_GPIO_Init_Port_Range(KeypadPORT,&PinCfg,7);
}

void delay(int x)
{
	unsigned i,j ;
	for(i=0; i<x; i++)
		for(j=0; j<255; j++);
}
int main(void)
{

	clock_init();
	GPIO_init();
	LCD_INIT();
//	LCD_WRITE_STRING("lcd is ready ...");
//	delay(500);
//	LCD_clear_screen();

	unsigned char LCD_DISPLAY [11] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};
	unsigned char DISPLAY [11] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};
	for (unsigned char i = 0; i < 11; i++) {
		LCD_WRITE_CHAR(LCD_DISPLAY[i]);
		MCAL_GPIO_WritePort(GPIOB, DISPLAY[i] << 9); /* write data on to the LED port */
		delay(500);
	}

	Keypad_Init();
//	LCD_WRITE_STRING("keypad is ready ...");
//	delay(500);
//	LCD_clear_screen();
	char keyinput ;

	while(1)
	{
		keyinput = Keypad_Getkey();

		switch(keyinput)
		{
		case 'A':
			break;
		case '?':
			LCD_clear_screen();
			break;
		default:
			LCD_WRITE_CHAR(keyinput);
			break;
		}

	}
}



