/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

//register address
#define GPIO_BASE	0x40010800
#define GPIO_CRH	*(vuint32_t *)(GPIO_BASE + 0x04)
#define GPIO_ODR	*(vuint32_t *)(GPIO_BASE + 0x0c)

#define RCC_BASE	0x40021000
#define RCC_APB2ENR		*(vuint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR		*(vuint32_t *)(RCC_BASE + 0x04)
#define RCC_CR			*(vuint32_t *)(RCC_BASE + 0x00)

int main(void)
{
	//GPIO Init
	GPIO_CRH  &= 0xFF0FFFFF ;
	GPIO_CRH  |= 0x00200000 ;

	//Init clock for GPIOA
	RCC_APB2ENR |= 1 << 2 ;


	//PLL Multiplication factor x8
	RCC_CFGR |= (0b0110 << 18);

	//PLL Enable
	RCC_CR |= 1 << 24 ;

	//Select PLL as System clock
	RCC_CFGR |= (0b10 << 0);

	//Set ABP2 prescaler
	RCC_CFGR |= (0b101 << 11);

	//Set ABP1 prescaler
	RCC_CFGR |= (0b100 << 8);


    /* Loop forever */
	while(1)
	{
		GPIO_ODR |= 1<<13 ;
		for(int i=0;i<5000;i++);
		GPIO_ODR &= ~(1<<13) ;
		for(int i=0;i<5000;i++);
	}
}
