/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32f103x6.h"
#include "Stm32_F103C6_GPIO_Driver.h"


void clock_init()
{
	//Init clock for GPIOA
	RCC_GPIOA_CLK_EN();

	//Init clock for GPIOB
	RCC_GPIOB_CLK_EN() ;
}

void GPIO_init()
{
	GPIO_PinConfig_t PinCfg ;

	//PORTA.1  input floating mode
	PinCfg.GPIO_PinNumber = GPIO_Pin_1 ;
	PinCfg.GPIO_Mode = GPIO_Mode_Input_FLO ;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//PORTA.13  input floating mode
	PinCfg.GPIO_PinNumber = GPIO_Pin_13 ;
	PinCfg.GPIO_Mode = GPIO_Mode_Input_FLO ;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//PORTB.1  output push pull mode
	PinCfg.GPIO_PinNumber = GPIO_Pin_1 ;
	PinCfg.GPIO_Mode = GPIO_Mode_Output_PP;
	PinCfg.GPIO_Output_Speed = GPIO_Speed_10M ;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	//PORTB.13  output push pull mode
	PinCfg.GPIO_PinNumber = GPIO_Pin_13 ;
	PinCfg.GPIO_Mode = GPIO_Mode_Output_PP ;
	PinCfg.GPIO_Output_Speed = GPIO_Speed_10M ;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

}

void delay(int x)
{
	unsigned i,j ;
	for(i=0; i<x; i++)
		for(j=0; j<255; j++);
}
int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_Pin_1) == 0) //pressed
		{
			MCAL_GPIO_TogglePin(GPIOB,GPIO_Pin_1) ;
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_Pin_1) == 0); //single press
		}

		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_Pin_13) == 1)  //multi press
		{
			MCAL_GPIO_TogglePin(GPIOB,GPIO_Pin_13) ;
		}

		delay(1);

	}

}


